#!/usr/bin/env python3
"""
flutter2frida_lab.py - flutter2frida adapted for this lab

Changes from upstream (aancw/flutter2frida v1.1.0):
  - x86_64 disassembly support (Nox emulator is x86_64)
  - Auto-detect arch from ELF header; --arch flag to override
  - Fix: APK analysis now happens inside the temp_directory context
  - Frida template updated for -H attach mode and x86_64 linker register
  - Usage line matches our frida -H 127.0.0.1:27042 workflow
"""

from __future__ import annotations

import argparse
import base64
import contextlib
import dataclasses
import datetime
import hashlib
import os
import re
import shutil
import string
import sys
import tempfile
import urllib.error
import urllib.request
import zipfile
from pathlib import Path
from typing import TYPE_CHECKING

try:
    import lief
except ImportError:
    sys.exit("[!] lief required: pip install lief")

try:
    from capstone import (
        CS_ARCH_ARM64, CS_MODE_ARM,
        CS_ARCH_X86, CS_MODE_64,
        Cs,
    )
except ImportError:
    sys.exit("[!] capstone required: pip install capstone")

if TYPE_CHECKING:
    from collections.abc import Iterator
    from typing import Optional

VERSION = "1.2.0-lab"


class Config:
    CHUNK_SIZE = 8192
    DISASM_CHUNK_SIZE = 0x20000
    PROLOGUE_SEARCH_RANGE = 512
    MAX_INSTRS_BACKWARD = 120
    ANALYSIS_INSTR_COUNT = 30
    ANALYSIS_CODE_SIZE = 200
    FETCH_TIMEOUT = 30
    BORINGSSL_FETCH_TIMEOUT = 60

    BORINGSSL_FILE_URL = (
        "https://boringssl.googlesource.com/boringssl/+/{rev}/ssl/ssl_x509.cc?format=TEXT"
    )
    ENGINEHASH_URL = (
        "https://raw.githubusercontent.com/Impact-I/reFlutter/main/enginehash.csv"
    )
    FLUTTER_DEPS_URL = (
        "https://raw.githubusercontent.com/flutter/flutter/refs/tags/{version}/DEPS"
    )


# ---------------------------------------------------------------------------
# Frida templates
# ---------------------------------------------------------------------------

_FRIDA_COMMON_HEADER = """/*
 * Flutter TLS Bypass - generated by flutter2frida_lab
 * Created:   CREATED_TIME
 * APK:       APK_NAME  (APK_SIZE)
 * SHA256:    APK_SHA256
 * Flutter:   FLUTTER_VERSION  (engine ENGINE_COMMIT)
 * Arch:      ARCH_NAME
 * Offset:    OFFSET_PLACEHOLDER
 *
 * Full intercept (spawn + proxy redirect):
 *   frida -H 127.0.0.1:27042 -f <package> -l config.js -l native-connect-hook.js -l this_script.js
 *
 * TLS bypass only (attach to running process):
 *   frida -H 127.0.0.1:27042 -n <process> -l this_script.js
 */
"""

# ARM64 variant - linker64 with x0 register for library path
FRIDA_TEMPLATE_ARM64 = _FRIDA_COMMON_HEADER + """
function attachNow() {
    var module = Process.findModuleByName("libflutter.so");
    if (!module) return false;
    console.log("[+] libflutter.so @ " + module.base);
    bypassVerify(module.base.add(OFFSET_PLACEHOLDER));
    return true;
}

function bypassVerify(address) {
    Interceptor.attach(address, {
        onLeave: function (retval) {
            retval.replace(0x1);
            console.log("[+] session_verify_cert_chain -> " + retval);
        }
    });
}

if (!attachNow()) {
    var do_dlopen = null;
    var call_constructor = null;
    Process.findModuleByName("linker64").enumerateSymbols().forEach(function (sym) {
        if (sym.name.indexOf("do_dlopen") >= 0)        do_dlopen = sym.address;
        if (sym.name.indexOf("call_constructor") >= 0) call_constructor = sym.address;
    });
    if (!do_dlopen || !call_constructor) {
        console.log("[-] linker64 symbols not found - attach after libflutter.so loads");
    } else {
        var loaded = false;
        Interceptor.attach(do_dlopen, function () {
            var path = this.context.x0.readCString();
            if (path && path.indexOf("libflutter.so") >= 0) {
                Interceptor.attach(call_constructor, function () {
                    if (!loaded) { loaded = true; attachNow(); }
                });
            }
        });
    }
}
"""

# x86_64 variant - linker64 with rdi register for library path
FRIDA_TEMPLATE_X86_64 = _FRIDA_COMMON_HEADER + """
function attachNow() {
    var module = Process.findModuleByName("libflutter.so");
    if (!module) return false;
    console.log("[+] libflutter.so @ " + module.base);
    bypassVerify(module.base.add(OFFSET_PLACEHOLDER));
    return true;
}

function bypassVerify(address) {
    Interceptor.attach(address, {
        onLeave: function (retval) {
            retval.replace(0x1);
            console.log("[+] session_verify_cert_chain -> " + retval);
        }
    });
}

if (!attachNow()) {
    var do_dlopen = null;
    var call_constructor = null;
    Process.findModuleByName("linker64").enumerateSymbols().forEach(function (sym) {
        if (sym.name.indexOf("do_dlopen") >= 0)        do_dlopen = sym.address;
        if (sym.name.indexOf("call_constructor") >= 0) call_constructor = sym.address;
    });
    if (!do_dlopen || !call_constructor) {
        console.log("[-] linker64 symbols not found - attach after libflutter.so loads");
    } else {
        var loaded = false;
        Interceptor.attach(do_dlopen, function () {
            var path = this.context.rdi.readCString();
            if (path && path.indexOf("libflutter.so") >= 0) {
                Interceptor.attach(call_constructor, function () {
                    if (!loaded) { loaded = true; attachNow(); }
                });
            }
        });
    }
}
"""


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclasses.dataclass(frozen=True)
class FileInfo:
    name: str
    size: int
    sha256: str

    @property
    def size_formatted(self) -> str:
        sz = self.size
        for unit in ["B", "KB", "MB", "GB"]:
            if sz < 1024:
                return f"{sz:.2f} {unit}"
            sz /= 1024
        return f"{sz:.2f} TB"


@dataclasses.dataclass
class FlutterVersion:
    version: str
    engine_commit: str


@dataclasses.dataclass
class FunctionCandidate:
    func_addr: int
    offset: int
    saved_regs: set
    has_frame_setup: bool   # stp x29/x30 (arm64) or push rbp (x86_64)
    has_sp_adjust: bool     # sub sp (arm64) or sub rsp (x86_64)
    mov_offset: int

    @property
    def score(self) -> int:
        score = 0
        if self.has_frame_setup and self.has_sp_adjust:
            score += 20
        elif self.has_sp_adjust:
            score += 10
        if 100 <= self.mov_offset <= 500:
            score += 15
        if len(self.saved_regs) >= 1:
            score += 5
        return score


@dataclasses.dataclass
class ErrorLineInfo:
    func_start_line: "Optional[int]"
    error_line: "Optional[int]"


# ---------------------------------------------------------------------------
# Arch detection
# ---------------------------------------------------------------------------

def detect_arch(libflutter_path: str) -> str:
    binary = lief.parse(libflutter_path)
    if binary is None:
        return "arm64"
    machine = str(binary.header.machine_type)
    if "x86_64" in machine.lower() or "X86_64" in machine:
        return "x86_64"
    if "AARCH64" in machine or "aarch64" in machine:
        return "arm64"
    return "arm64"


# ---------------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------------

@contextlib.contextmanager
def temp_directory() -> "Iterator[str]":
    tmpdir = tempfile.mkdtemp(prefix="flutter_tls_")
    try:
        yield tmpdir
    finally:
        if os.path.exists(tmpdir):
            shutil.rmtree(tmpdir)


def get_file_info(file_path: str) -> "Optional[FileInfo]":
    if not file_path or not os.path.exists(file_path):
        return None
    sha256 = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(Config.CHUNK_SIZE), b""):
            sha256.update(chunk)
    return FileInfo(
        name=os.path.basename(file_path),
        size=os.path.getsize(file_path),
        sha256=sha256.hexdigest(),
    )


def get_snapshot_hash(file_path: str) -> "Optional[str]":
    with open(file_path, errors="ignore") as f:
        result = ""
        for ch in f.read():
            if ch in string.printable:
                result += ch
                continue
            if len(result) >= 32:
                match = re.findall(r"([a-f\d]{32})", result)
                if match:
                    return match[0]
            result = ""
    return None


def fetch_url(url: str, timeout: int = Config.FETCH_TIMEOUT) -> "Optional[str]":
    try:
        with urllib.request.urlopen(url, timeout=timeout) as resp:
            return resp.read().decode("utf-8")
    except (urllib.error.URLError, urllib.error.HTTPError, UnicodeDecodeError):
        return None


def find_flutter_version(
    snapshot_hash: str, enginehash_path: "Optional[str]" = None
) -> "Optional[FlutterVersion]":
    csv = None
    if enginehash_path and os.path.exists(enginehash_path):
        with open(enginehash_path) as f:
            csv = f.read()
    else:
        csv = fetch_url(Config.ENGINEHASH_URL)
    if not csv:
        return None
    for line in csv.strip().split("\n"):
        if snapshot_hash in line:
            parts = line.split(",")
            if len(parts) >= 2:
                return FlutterVersion(version=parts[0], engine_commit=parts[1])
    return None


def get_boringssl_revision(version: str) -> "Optional[str]":
    deps = fetch_url(Config.FLUTTER_DEPS_URL.format(version=version))
    if not deps:
        return None
    match = re.search(r"'dart_boringssl_rev':\s*'([a-f0-9]+)'", deps)
    return match.group(1) if match else None


def fetch_boringssl_file(rev: str) -> "Optional[str]":
    url = Config.BORINGSSL_FILE_URL.format(rev=rev)
    try:
        with urllib.request.urlopen(url, timeout=Config.BORINGSSL_FETCH_TIMEOUT) as resp:
            return base64.b64decode(resp.read()).decode("utf-8")
    except (urllib.error.URLError, urllib.error.HTTPError, UnicodeDecodeError):
        return None


def find_error_line_number(content: str) -> ErrorLineInfo:
    lines = content.split("\n")
    func_start = None
    error_line = None
    for i, line in enumerate(lines, 1):
        if "static bool ssl_crypto_x509_session_verify_cert_chain" in line:
            func_start = i
        if func_start and "OPENSSL_PUT_ERROR" in line:
            error_line = i
            break
    return ErrorLineInfo(func_start_line=func_start, error_line=error_line)


# ---------------------------------------------------------------------------
# ARM64 disassembly
# ---------------------------------------------------------------------------

def find_mov_candidates_arm64(
    data: bytes, text_offset: int, text_size: int, scalar: int
) -> list:
    md = Cs(CS_ARCH_ARM64, CS_MODE_ARM)
    candidates = []
    for off in range(text_offset, text_offset + text_size, Config.DISASM_CHUNK_SIZE):
        chunk = data[off: min(off + Config.DISASM_CHUNK_SIZE, text_offset + text_size)]
        for ins in md.disasm(chunk, off):
            if ins.mnemonic == "mov":
                if f"#{scalar}" in ins.op_str or f"#0x{scalar:x}" in ins.op_str:
                    candidates.append(ins.address)
    return candidates


def find_prologue_arm64(data: bytes, addr: int, md: Cs) -> "Optional[int]":
    start = max(addr - Config.PROLOGUE_SEARCH_RANGE, 0)
    chunk = data[start: addr + 8]
    instrs = list(md.disasm(chunk, start))
    target_idx = next((i for i, ins in enumerate(instrs) if ins.address == addr), None)
    if target_idx is None:
        return None
    for idx in range(target_idx, max(target_idx - Config.MAX_INSTRS_BACKWARD, 0), -1):
        ins = instrs[idx]
        is_prologue = (
            (ins.mnemonic == "sub" and "sp, sp," in ins.op_str)
            or (ins.mnemonic == "stp" and "x29, x30" in ins.op_str)
            or (ins.mnemonic == "stp" and "[sp," in ins.op_str)
            or (ins.mnemonic == "str" and "x30," in ins.op_str and "[sp," in ins.op_str)
        )
        if is_prologue:
            if idx == 0:
                return ins.address
            prev = instrs[idx - 1]
            if prev.mnemonic in ("ret", "b", "br", "brk"):
                return ins.address
    return None


def analyze_function_arm64(
    data: bytes, func_addr: int, md: Cs
) -> tuple:
    chunk = data[func_addr: func_addr + Config.ANALYSIS_CODE_SIZE]
    instrs = list(md.disasm(chunk, func_addr))
    saved = set()
    has_frame = False
    has_sp_adj = False
    callee_saved = {f"x{n}" for n in range(19, 30)} | {"x29"}
    for ins in instrs[: Config.ANALYSIS_INSTR_COUNT]:
        if ins.mnemonic == "stp" and "x29, x30" in ins.op_str:
            has_frame = True
        if ins.mnemonic == "sub" and "sp, sp," in ins.op_str:
            has_sp_adj = True
        if ins.mnemonic == "stp":
            for reg in callee_saved:
                if reg in ins.op_str:
                    saved.add(reg)
        if ins.mnemonic in ("bl", "b"):
            break
    return saved, has_frame, has_sp_adj


# ---------------------------------------------------------------------------
# x86_64 disassembly
# ---------------------------------------------------------------------------

def find_mov_candidates_x86_64(
    data: bytes, text_offset: int, text_size: int, scalar: int
) -> list:
    from capstone.x86_const import X86_OP_IMM
    md = Cs(CS_ARCH_X86, CS_MODE_64)
    md.detail = True
    candidates = []
    for off in range(text_offset, text_offset + text_size, Config.DISASM_CHUNK_SIZE):
        chunk = data[off: min(off + Config.DISASM_CHUNK_SIZE, text_offset + text_size)]
        for ins in md.disasm(chunk, off):
            if ins.mnemonic not in ("mov", "movabs", "movsx", "movzx"):
                continue
            for op in ins.operands:
                if op.type == X86_OP_IMM and op.imm == scalar:
                    candidates.append(ins.address)
                    break
    return candidates


def find_prologue_x86_64(data: bytes, addr: int, md: Cs) -> "Optional[int]":
    start = max(addr - Config.PROLOGUE_SEARCH_RANGE, 0)
    chunk = data[start: addr + 8]
    instrs = list(md.disasm(chunk, start))
    target_idx = next((i for i, ins in enumerate(instrs) if ins.address == addr), None)
    if target_idx is None:
        return None
    for idx in range(target_idx, max(target_idx - Config.MAX_INSTRS_BACKWARD, 0), -1):
        ins = instrs[idx]
        # x86_64 function prologue patterns
        is_prologue = (
            (ins.mnemonic == "push" and ins.op_str == "rbp")
            or (ins.mnemonic == "sub" and "rsp," in ins.op_str)
            or (ins.mnemonic == "push" and ins.op_str in ("r15", "r14", "r13", "r12", "rbx"))
        )
        if is_prologue:
            if idx == 0:
                return ins.address
            prev = instrs[idx - 1]
            if prev.mnemonic in ("ret", "jmp", "int3", "nop", "endbr64"):
                return ins.address
            # Also accept if previous is a return-like cc (0xcc = int3 padding)
            if prev.mnemonic == "int3":
                return ins.address
    return None


def analyze_function_x86_64(
    data: bytes, func_addr: int, text_offset: int, text_va: int
) -> tuple:
    file_off = text_offset + (func_addr - text_va)
    chunk = data[file_off: file_off + Config.ANALYSIS_CODE_SIZE]
    md = Cs(CS_ARCH_X86, CS_MODE_64)
    md.detail = False
    instrs = list(md.disasm(chunk, func_addr))
    saved = set()
    has_frame = False
    has_sp_adj = False
    callee_saved = {"rbx", "rbp", "r12", "r13", "r14", "r15"}
    for ins in instrs[: Config.ANALYSIS_INSTR_COUNT]:
        if ins.mnemonic == "push" and ins.op_str == "rbp":
            has_frame = True
        if ins.mnemonic == "sub" and "rsp," in ins.op_str:
            has_sp_adj = True
        if ins.mnemonic == "push" and ins.op_str in callee_saved:
            saved.add(ins.op_str)
        if ins.mnemonic in ("call",):
            break
    return saved, has_frame, has_sp_adj


def find_function_offset_x86_64(
    data: bytes, text: "object", image_base: int, error_line: int, verbose: bool
) -> "Optional[FunctionCandidate]":
    import bisect
    from capstone.x86_const import X86_OP_IMM

    text_va = text.virtual_address
    md = Cs(CS_ARCH_X86, CS_MODE_64)
    md.detail = True

    if verbose:
        print(f"[*] x86_64 forward scan: building func-start list + finding MOV imm={error_line} ...")

    func_starts = []
    mov_candidates = []
    prev_was_ret = True

    for off in range(text.offset, text.offset + text.size, Config.DISASM_CHUNK_SIZE):
        chunk_end = min(off + Config.DISASM_CHUNK_SIZE, text.offset + text.size)
        chunk = data[off:chunk_end]
        chunk_va = text_va + (off - text.offset)
        for ins in md.disasm(chunk, chunk_va):
            # track function starts (ret-only boundaries)
            if prev_was_ret and ins.mnemonic not in ("int3", "nop"):
                func_starts.append(ins.address)
                prev_was_ret = False
            if ins.mnemonic == "ret":
                prev_was_ret = True
            elif ins.mnemonic not in ("int3", "nop"):
                prev_was_ret = False

            # find MOV with exact immediate == error_line
            if ins.mnemonic in ("mov", "movabs", "movsx", "movzx"):
                for op in ins.operands:
                    if op.type == X86_OP_IMM and op.imm == error_line:
                        mov_candidates.append(ins.address)
                        break

    if verbose:
        print(f"[+] {len(func_starts)} function starts, {len(mov_candidates)} MOV-{error_line} candidates")

    results = []
    seen = set()
    for mov_addr in mov_candidates:
        idx = bisect.bisect_right(func_starts, mov_addr) - 1
        if idx < 0:
            continue
        func_va = func_starts[idx]
        if func_va in seen:
            continue
        seen.add(func_va)

        saved, has_frame, has_sp_adj = analyze_function_x86_64(
            data, func_va, text.offset, text_va
        )
        offset = func_va - image_base
        mov_offset = mov_addr - func_va
        c = FunctionCandidate(
            func_addr=func_va,
            offset=offset,
            saved_regs=saved,
            has_frame_setup=has_frame,
            has_sp_adjust=has_sp_adj,
            mov_offset=mov_offset,
        )
        results.append(c)
        if verbose:
            tag = "[std prologue]" if (has_frame and has_sp_adj) else ""
            print(f"    func=0x{func_va:08x}  offset=0x{offset:08x}  mov_delta={mov_offset}  {tag}")

    if not results:
        return None
    return max(results, key=lambda r: r.score)


# ---------------------------------------------------------------------------
# Unified offset finder
# ---------------------------------------------------------------------------

def find_function_offset(
    libflutter_path: str, error_line: int, arch: str, verbose: bool = True
) -> "Optional[FunctionCandidate]":
    binary = lief.parse(libflutter_path)
    if binary is None:
        print("[!] lief could not parse libflutter.so")
        return None

    with open(libflutter_path, "rb") as f:
        data = f.read()

    text = next((s for s in binary.sections if s.name == ".text"), None)
    if not text:
        print("[!] .text section not found")
        return None

    image_base = binary.imagebase

    if verbose:
        print(f"[*] image_base=0x{image_base:x}  arch={arch}  error_line={error_line}")

    if arch == "x86_64":
        return find_function_offset_x86_64(data, text, image_base, error_line, verbose)

    # ARM64 path
    md = Cs(CS_ARCH_ARM64, CS_MODE_ARM)
    candidates_addr = find_mov_candidates_arm64(data, text.offset, text.size, error_line)
    if verbose:
        print(f"[+] MOV candidates: {len(candidates_addr)}")

    results = []
    seen = set()
    for mov_addr in candidates_addr:
        func_addr = find_prologue_arm64(data, mov_addr, md)
        if not func_addr or func_addr in seen:
            continue
        seen.add(func_addr)
        saved, has_frame, has_sp_adj = analyze_function_arm64(data, func_addr, md)
        offset = func_addr - image_base
        mov_offset = mov_addr - func_addr
        c = FunctionCandidate(
            func_addr=func_addr,
            offset=offset,
            saved_regs=saved,
            has_frame_setup=has_frame,
            has_sp_adjust=has_sp_adj,
            mov_offset=mov_offset,
        )
        results.append(c)
        if verbose:
            tag = "[std prologue]" if (has_frame and has_sp_adj) else ""
            print(f"    func=0x{func_addr:08x}  offset=0x{offset:08x}  mov_delta={mov_offset}  {tag}")

    if not results:
        return None
    return max(results, key=lambda r: r.score)


# ---------------------------------------------------------------------------
# APK / directory handling
# ---------------------------------------------------------------------------

def extract_apk(apk_path: str, temp_dir: str, preferred_arch: str) -> tuple:
    print(f"[*] Extracting {apk_path}")
    with zipfile.ZipFile(apk_path, "r") as zf:
        zf.extractall(temp_dir)

    lib_dir = os.path.join(temp_dir, "lib")
    if not os.path.exists(lib_dir):
        return None, None

    archs = [a for a in os.listdir(lib_dir) if os.path.isdir(os.path.join(lib_dir, a))]
    if not archs:
        return None, None

    # Preference order based on --arch flag
    pref_map = {
        "x86_64": ["x86_64", "arm64-v8a", "armeabi-v7a", "x86"],
        "arm64":  ["arm64-v8a", "x86_64", "armeabi-v7a", "x86"],
    }
    order = pref_map.get(preferred_arch, pref_map["arm64"])
    selected = next((a for a in order if a in archs), archs[0])
    print(f"[*] archs={archs}  selected={selected}")

    arch_path = os.path.join(lib_dir, selected)
    libapp = os.path.join(arch_path, "libapp.so")
    libflutter = os.path.join(arch_path, "libflutter.so")

    if not os.path.exists(libapp):
        print(f"[!] libapp.so not found in {arch_path}")
        return None, None
    if not os.path.exists(libflutter):
        print(f"[!] libflutter.so not found in {arch_path}")
        return None, None

    return libapp, libflutter


def scan_directory(directory: str) -> tuple:
    libapp = libflutter = None
    for root, _, files in os.walk(directory):
        for f in files:
            if f == "libapp.so":
                libapp = os.path.join(root, f)
            elif f == "libflutter.so":
                libflutter = os.path.join(root, f)
    return libapp, libflutter


# ---------------------------------------------------------------------------
# Script generation
# ---------------------------------------------------------------------------

_CONFIG_JS_TEMPLATE = """\
// flutter2frida config - generated by flutter2frida_lab
// Load this BEFORE native-connect-hook.js
// Update CERT_PEM if mitmproxy CA is regenerated.

const CERT_PEM = `CERT_PEM_PLACEHOLDER`;

const PROXY_HOST = 'PROXY_HOST_PLACEHOLDER';
const PROXY_PORT = PROXY_PORT_PLACEHOLDER;

const DEBUG_MODE = false;
const IGNORED_NON_HTTP_PORTS = [];
const BLOCK_HTTP3 = true;
const PROXY_SUPPORTS_SOCKS5 = false;

// --- httptoolkit boilerplate (required by native-connect-hook.js) ----------

console.log('');

const BASE64_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';
const BASE64_LOOKUP = new Uint8Array(123);
for (let i = 0; i < BASE64_CHARS.length; i++) {
    BASE64_LOOKUP[BASE64_CHARS.charCodeAt(i)] = i;
}
function decodeBase64(input) {
    let outputLength = Math.floor((input.length * 3) / 4);
    if (input[input.length - 1] === '=') outputLength--;
    if (input[input.length - 2] === '=') outputLength--;
    const output = new Uint8Array(outputLength);
    let outputPos = 0;
    for (let i = 0; i < input.length; i += 4) {
        const a = BASE64_LOOKUP[input.charCodeAt(i)];
        const b = BASE64_LOOKUP[input.charCodeAt(i + 1)];
        const c = BASE64_LOOKUP[input.charCodeAt(i + 2)];
        const d = BASE64_LOOKUP[input.charCodeAt(i + 3)];
        const chunk = (a << 18) | (b << 12) | (c << 6) | d;
        output[outputPos++] = (chunk >> 16) & 0xff;
        if (input.charCodeAt(i + 2) !== 61) output[outputPos++] = (chunk >> 8) & 0xff;
        if (input.charCodeAt(i + 3) !== 61) output[outputPos++] = chunk & 0xff;
    }
    return output;
}
function pemToDer(input) {
    const pemLines = input.split('\\n');
    const base64Data = pemLines.slice(1, -1).map(l => l.trim()).join('');
    return decodeBase64(base64Data);
}
const CERT_DER = pemToDer(CERT_PEM);

const MODULE_LOAD_CALLBACKS = {};
const getModuleName = (p) => p.slice(p.lastIndexOf('/') + 1);
new ApiResolver('module').enumerateMatches('exports:linker*!*dlopen*').forEach((dlopen) => {
    Interceptor.attach(dlopen.address, {
        onEnter(args) {
            const m = args[0].readCString();
            if (m) { this.path = m; this.moduleName = getModuleName(m); }
        },
        onLeave(retval) {
            if (!this.path || !retval || retval.isNull()) return;
            if (!MODULE_LOAD_CALLBACKS[this.moduleName]) return;
            const mod = Process.findModuleByName(this.moduleName) ?? Process.findModuleByAddress(retval);
            if (mod) { MODULE_LOAD_CALLBACKS[this.moduleName](mod); delete MODULE_LOAD_CALLBACKS[this.moduleName]; }
        }
    });
});
function waitForModule(moduleName, callback) {
    if (Array.isArray(moduleName)) { moduleName.forEach(m => waitForModule(m, callback)); return; }
    try { const m = Process.getModuleByName(moduleName); m.ensureInitialized(); callback(m); return; } catch(e) {}
    try { callback(Module.load(moduleName)); return; } catch(e) {}
    MODULE_LOAD_CALLBACKS[moduleName] = callback;
}
"""

DEFAULT_CERT_PATHS = [
    os.path.expanduser("~/.mitmproxy/mitmproxy-ca-cert.pem"),
    "C:/Users/dhava/.mitmproxy/mitmproxy-ca-cert.pem",
]


def generate_config_js(output_path: str, proxy_host: str, proxy_port: int,
                       cert_path: "Optional[str]") -> bool:
    cert_pem = None
    candidates = ([cert_path] if cert_path else []) + DEFAULT_CERT_PATHS
    for p in candidates:
        if p and os.path.exists(p):
            with open(p) as f:
                cert_pem = f.read().strip()
            print(f"[*] CA cert: {p}")
            break

    if not cert_pem:
        print("[!] CA cert not found - pass --cert <path> or place mitmproxy-ca-cert.pem in ~/.mitmproxy/")
        return False

    js = _CONFIG_JS_TEMPLATE
    js = js.replace("CERT_PEM_PLACEHOLDER", cert_pem)
    js = js.replace("PROXY_HOST_PLACEHOLDER", proxy_host)
    js = js.replace("PROXY_PORT_PLACEHOLDER", str(proxy_port))

    with open(output_path, "w") as f:
        f.write(js)
    return True


def generate_frida_script(
    output_path: str,
    offset: int,
    version: str,
    engine_commit: str,
    arch: str,
    apk_info: "Optional[FileInfo]" = None,
    libapp_name: "Optional[str]" = None,
) -> None:
    template = FRIDA_TEMPLATE_X86_64 if arch == "x86_64" else FRIDA_TEMPLATE_ARM64
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    apk_name = apk_info.name if apk_info else (libapp_name or "unknown")
    apk_size = apk_info.size_formatted if apk_info else "N/A"
    apk_sha256 = apk_info.sha256 if apk_info else "N/A"
    offset_str = f"0x{offset:08x}"

    script = template
    script = script.replace("CREATED_TIME",       now)
    script = script.replace("APK_NAME",           apk_name)
    script = script.replace("APK_SIZE",           apk_size)
    script = script.replace("APK_SHA256",         apk_sha256)
    script = script.replace("FLUTTER_VERSION",    version)
    script = script.replace("ENGINE_COMMIT",      engine_commit)
    script = script.replace("ARCH_NAME",          arch)
    script = script.replace("OFFSET_PLACEHOLDER", offset_str)

    with open(output_path, "w") as f:
        f.write(script)


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def run_analysis(libapp_path: str, libflutter_path: str, arch: str,
                 enginehash_path: "Optional[str]", output_path: str,
                 apk_info: "Optional[FileInfo]", verbose: bool,
                 proxy: "Optional[str]" = None,
                 cert: "Optional[str]" = None) -> int:

    # 1. Snapshot hash -> Flutter version
    print(f"\n[*] libapp:    {libapp_path}")
    print(f"[*] libflutter: {libflutter_path}")

    snapshot_hash = get_snapshot_hash(libapp_path)
    if not snapshot_hash:
        print("[!] Could not extract snapshot hash from libapp.so")
        return 1
    print(f"[+] snapshot hash: {snapshot_hash}")

    flutter_version = find_flutter_version(snapshot_hash, enginehash_path)
    if not flutter_version:
        print(f"[!] Version not found for hash {snapshot_hash}")
        print("    Rebuild enginehash.csv: https://github.com/Impact-I/reFlutter scripts/gen_enginehash.py")
        print("    Then pass with -e enginehash.csv")
        return 1
    print(f"[+] Flutter {flutter_version.version}  engine {flutter_version.engine_commit}")

    # 2. BoringSSL error line
    boringssl_rev = get_boringssl_revision(flutter_version.version)
    if not boringssl_rev:
        print("[!] Could not find BoringSSL revision in Flutter DEPS")
        return 1
    print(f"[+] BoringSSL rev: {boringssl_rev}")

    ssl_x509 = fetch_boringssl_file(boringssl_rev)
    if not ssl_x509:
        print("[!] Could not fetch ssl_x509.cc from BoringSSL")
        return 1

    error_info = find_error_line_number(ssl_x509)
    if not error_info.error_line:
        print("[!] OPENSSL_PUT_ERROR line not found in ssl_x509.cc")
        return 1
    print(f"[+] OPENSSL_PUT_ERROR line: {error_info.error_line}")

    # 3. Auto-detect arch if not forced
    if arch == "auto":
        arch = detect_arch(libflutter_path)
        print(f"[*] Detected arch: {arch}")

    # 4. Find function offset
    candidate = find_function_offset(libflutter_path, error_info.error_line, arch, verbose)
    if not candidate:
        print("[!] Could not locate target function in libflutter.so")
        return 1

    offset_str = f"0x{candidate.offset:08x}"
    print(f"\n[+] Function: 0x{candidate.func_addr:08x}")
    print(f"[+] Offset:   {offset_str}")
    print(f"[+] Score:    {candidate.score}")

    # 5. Generate script
    generate_frida_script(
        output_path=output_path,
        offset=candidate.offset,
        version=flutter_version.version,
        engine_commit=flutter_version.engine_commit,
        arch=arch,
        apk_info=apk_info,
        libapp_name=os.path.basename(libapp_path),
    )
    print(f"\n[+] Script: {output_path}")

    # Optional: generate config.js for native-connect-hook proxy redirection
    config_generated = False
    if proxy:
        if ":" in proxy:
            proxy_host, proxy_port_str = proxy.rsplit(":", 1)
            try:
                proxy_port = int(proxy_port_str)
            except ValueError:
                print(f"[!] Invalid proxy port in '{proxy}'")
                proxy_host, proxy_port = proxy, 8080
        else:
            proxy_host, proxy_port = proxy, 8080

        config_out = os.path.join(os.path.dirname(os.path.abspath(output_path)), "config.js")
        config_generated = generate_config_js(config_out, proxy_host, proxy_port, cert)
        if config_generated:
            print(f"[+] Config: {config_out}  (proxy={proxy_host}:{proxy_port})")

    hook_js = os.path.join(os.path.dirname(os.path.abspath(output_path)), "native-connect-hook.js")
    if config_generated and os.path.exists(hook_js):
        print(f"\n[+] Full intercept (spawn):")
        print(f"    frida -H 127.0.0.1:27042 -f <package> \\")
        print(f"        -l config.js -l native-connect-hook.js -l {os.path.basename(output_path)}")
    else:
        print(f"[+] TLS bypass only:")
        print(f"    frida -H 127.0.0.1:27042 -n <process> -l {output_path}")

    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="flutter2frida_lab - TLS bypass script generator (x86_64 + arm64)"
    )
    parser.add_argument("target", nargs="?", help="APK file or extracted directory")
    parser.add_argument("--libapp",     "-a", help="libapp.so path")
    parser.add_argument("--libflutter", "-f", help="libflutter.so path")
    parser.add_argument("--output",     "-o", default="disable-flutter-tls.js")
    parser.add_argument("--enginehash", "-e", help="local enginehash.csv")
    parser.add_argument(
        "--arch",
        choices=["auto", "arm64", "x86_64"],
        default="auto",
        help="Force architecture (default: auto-detect from ELF header)",
    )
    parser.add_argument(
        "--proxy", "-p",
        metavar="HOST:PORT",
        help="Proxy address for native-connect-hook (e.g. 172.17.99.2:8080); generates config.js",
    )
    parser.add_argument(
        "--cert",
        metavar="PEM",
        help="CA cert PEM file for config.js (default: ~/.mitmproxy/mitmproxy-ca-cert.pem)",
    )
    parser.add_argument("--quiet", "-q", action="store_true")
    parser.add_argument("--version", "-V", action="version", version=f"%(prog)s {VERSION}")
    args = parser.parse_args()

    verbose = not args.quiet
    libapp_path = args.libapp
    libflutter_path = args.libflutter
    apk_info = None

    if libapp_path and libflutter_path:
        # Direct .so paths - run analysis immediately
        return run_analysis(
            libapp_path, libflutter_path,
            args.arch, args.enginehash, args.output,
            apk_info, verbose,
            proxy=args.proxy, cert=args.cert,
        )

    if not args.target:
        parser.print_help()
        return 1

    target = args.target

    if os.path.isfile(target) and target.endswith(".apk"):
        apk_info = get_file_info(target)
        # NOTE: extraction happens inside the with block so files exist during analysis
        with temp_directory() as tmpdir:
            libapp_path, libflutter_path = extract_apk(target, tmpdir, args.arch)
            if not libapp_path or not libflutter_path:
                return 1
            return run_analysis(
                libapp_path, libflutter_path,
                args.arch, args.enginehash, args.output,
                apk_info, verbose,
                proxy=args.proxy, cert=args.cert,
            )

    elif os.path.isdir(target):
        libapp_path, libflutter_path = scan_directory(target)
        if not libapp_path or not libflutter_path:
            print("[!] Could not find libapp.so / libflutter.so in directory")
            return 1
        return run_analysis(
            libapp_path, libflutter_path,
            args.arch, args.enginehash, args.output,
            apk_info, verbose,
            proxy=args.proxy, cert=args.cert,
        )
    else:
        print(f"[!] Invalid target: {target}")
        return 1


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\n[*] Interrupted")
        sys.exit(0)
